/*
DROP TABLE PRODUTO_CP;
CREATE TABLE PRODUTO_Cp(
    codigo number (4),
    categoria char(1),
    valor number(4,2)
);

INSERT INTO PRODUTO_Cp VALUES (1001, 'A', 7.55);
INSERT INTO PRODUTO_Cp VALUES (1002, 'B', 5.95);
INSERT INTO PRODUTO_Cp VALUES (1003, 'C', 3.45);
*/

SET SERVEROUTPUT ON
DECLARE
    CURSOR C_PRODUTO IS SELECT CATEGORIA, VALOR FROM PRODUTO_Cp;
BEGIN
    FOR REG IN C_PRODUTO LOOP
        IF REG.CATEGORIA = 'A' THEN
             UPDATE PRODUTO_Cp SET VALOR = REG.VALOR * 1.05 WHERE CATEGORIA = REG.CATEGORIA;
        ELSIF REG.CATEGORIA = 'B' THEN
            UPDATE PRODUTO_Cp SET VALOR = REG.VALOR * 1.1 WHERE CATEGORIA = REG.CATEGORIA;
        ELSE
            UPDATE PRODUTO_Cp SET VALOR = REG.VALOR * 1.15 WHERE CATEGORIA = REG.CATEGORIA;
        END IF;
    END LOOP;
END;