SET SERVEROUTPUT ON
DECLARE
    V_TABUADA NUMBER(10) := &TABUADA;
    V_CONTADOR NUMBER(2) := 0;
    V_RESPOSTA NUMBER (10);
BEGIN
    LOOP
        V_RESPOSTA := V_TABUADA * V_CONTADOR;
        DBMS_OUTPUT.PUT_LINE(V_TABUADA || ' x ' || V_CONTADOR || ' = ' || V_RESPOSTA);
        V_CONTADOR := V_CONTADOR + 1;
        EXIT WHEN V_CONTADOR = 10;
    END LOOP;
END;