/*
CREATE TABLE cliente (
    id_cliente NUMBER(10) NOT NULL,
    nm_cliente VARCHAR2(100) NOT NULL,
    nr_idade   NUMBER(3)
);

ALTER TABLE cliente ADD CONSTRAINT cliente_pk PRIMARY KEY ( id_cliente );

CREATE TABLE pedido (
    nr_pedido          NUMBER(9) NOT NULL,
    dt_pedido          DATE NOT NULL,
    fk_id_cliente NUMBER(10) NOT NULL
);

ALTER TABLE pedido ADD CONSTRAINT pedido_pk PRIMARY KEY ( nr_pedido );

ALTER TABLE pedido
    ADD CONSTRAINT pedido_cliente_fk FOREIGN KEY ( fk_id_cliente )
        REFERENCES cliente ( id_cliente );


INSERT INTO CLIENTE (ID_CLIENTE, NM_CLIENTE, NR_IDADE) VALUES (1, 'Matheus', 19);
INSERT INTO CLIENTE (ID_CLIENTE, NM_CLIENTE, NR_IDADE) VALUES (2, 'Diogo', 80);
INSERT INTO CLIENTE (ID_CLIENTE, NM_CLIENTE, NR_IDADE) VALUES (3, 'José', 40);

INSERT INTO PEDIDO (NR_PEDIDO, DT_PEDIDO, FK_ID_CLIENTE) VALUES (1, TO_DATE('03.12.2004','DD.MM.YYYY'), 1);
INSERT INTO PEDIDO (NR_PEDIDO, DT_PEDIDO, FK_ID_CLIENTE) VALUES (2, TO_DATE('03.12.2005','DD.MM.YYYY'), 1);
INSERT INTO PEDIDO (NR_PEDIDO, DT_PEDIDO, FK_ID_CLIENTE) VALUES (3, TO_DATE('03.12.2010','DD.MM.YYYY'), 2);
INSERT INTO PEDIDO (NR_PEDIDO, DT_PEDIDO, FK_ID_CLIENTE) VALUES (4, TO_DATE('03.12.2011','DD.MM.YYYY'), 2);
COMMIT;
*/

CREATE OR REPLACE PROCEDURE SP_LISTAR_CLIENTES IS
    CURSOR C_PEDIDOS IS 
        SELECT C.ID_CLIENTE,
            C.NM_CLIENTE AS NOME,
            C.NR_IDADE AS IDADE,
            P.NR_PEDIDO AS NR_PEDIDO,
            P.DT_PEDIDO AS DT_PEDIDO
    FROM CLIENTE C INNER JOIN PEDIDO P ON (C.ID_CLIENTE = P.FK_ID_CLIENTE);

BEGIN
    FOR REG IN C_PEDIDOS LOOP
        DBMS_OUTPUT.PUT_LINE('NOME: ' || REG.NOME);
        DBMS_OUTPUT.PUT_LINE('IDADE: ' || REG.IDADE);
        DBMS_OUTPUT.PUT_LINE('NÚMERO DO PEDIDO: ' || REG.NR_PEDIDO);
        DBMS_OUTPUT.PUT_LINE('DATA DO PEDIDO: ' || REG.DT_PEDIDO);
        DBMS_OUTPUT.PUT_LINE('');
    END LOOP;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Erro: ' || SQLCODE);
        DBMS_OUTPUT.PUT_LINE('Mensagem - ' || SQLERRM);

end;

/* SCRIPT COM SELECT JOIN
DECLARE
    V_ID_CLIENTE NUMBER(10);
    V_NM_CLIENTE VARCHAR2(100);
    V_NR_IDADE NUMBER(3);
    V_NR_PEDIDO NUMBER(10);
    V_DT_PEDIDO DATE;
    V_FK_ID_CLIENTE NUMBER(10);

BEGIN
    SELECT C.ID_CLIENTE, C.NM_CLIENTE, C.NR_IDADE, P.NR_PEDIDO, P.DT_PEDIDO, P.FK_ID_CLIENTE
        INTO V_ID_CLIENTE, V_NM_CLIENTE, V_NR_IDADE, V_NR_PEDIDO,V_DT_PEDIDO, V_FK_ID_CLIENTE
        FROM CLIENTE C
        INNER JOIN PEDIDO P
        ON C.ID_CLIENTE = P.FK_ID_CLIENTE; 
END;
*/