/*
CREATE TABLE FUNC(
    id_func numeric(9) primary key,
    nome varchar2(50),
    salario numeric (9,2)
)

create or replace PROCEDURE SP_AJUSTE_SALARIO(NOVO_ID_FUNC IN NUMERIC, NOVO_NOME IN VARCHAR2, NOVO_SALARIO IN NUMERIC) IS
BEGIN
INSERT INTO FUNC (ID_FUNC, NOME, SALARIO) VALUES (NOVO_ID_FUNC, NOVO_NOME, NOVO_SALARIO);
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERRO NO PROCEDIMENTO');
END;
/
*/
SET SERVEROUTPUT ON
DECLARE
V_ID_FUNC NUMERIC(9):= '&ID';
V_NOME VARCHAR2(50):= '&NOME';
V_SALARIO NUMERIC(9,2):= '&SALARIO';
BEGIN
    SP_AJUSTE_SALARIO(V_ID_FUNC, V_NOME, V_SALARIO);
    DBMS_OUTPUT.PUT_LINE('DADOS INSERIDOS NA TABELA');
END;