SET SERVEROUTPUT ON
DECLARE
    V_TABUADA NUMBER(10) := &TABUADA;
    V_RESPOSTA NUMBER (10);
BEGIN
    FOR V_CONTADOR IN 1..10 LOOP
        V_RESPOSTA := V_TABUADA * V_CONTADOR;
        DBMS_OUTPUT.PUT_LINE(V_TABUADA || ' x ' || V_CONTADOR || ' = ' || V_RESPOSTA);
    END LOOP;
END;