/*
CREATE TABLE cliente (
    id_cliente NUMBER(10) NOT NULL,
    nm_cliente VARCHAR2(100) NOT NULL,
    nr_idade   NUMBER(3)
);

ALTER TABLE cliente ADD CONSTRAINT cliente_pk PRIMARY KEY ( id_cliente );

CREATE TABLE pedido (
    nr_pedido          NUMBER(9) NOT NULL,
    dt_pedido          DATE NOT NULL,
    fk_id_cliente NUMBER(10) NOT NULL
);

ALTER TABLE pedido ADD CONSTRAINT pedido_pk PRIMARY KEY ( nr_pedido );

ALTER TABLE pedido
    ADD CONSTRAINT pedido_cliente_fk FOREIGN KEY ( fk_id_cliente )
        REFERENCES cliente ( id_cliente );


INSERT INTO CLIENTE (ID_CLIENTE, NM_CLIENTE, NR_IDADE) VALUES (1, 'Matheus', 19);
INSERT INTO CLIENTE (ID_CLIENTE, NM_CLIENTE, NR_IDADE) VALUES (2, 'Diogo', 80);
INSERT INTO CLIENTE (ID_CLIENTE, NM_CLIENTE, NR_IDADE) VALUES (3, 'José', 40);

INSERT INTO PEDIDO (NR_PEDIDO, DT_PEDIDO, FK_ID_CLIENTE) VALUES (1, TO_DATE('03.12.2004','DD.MM.YYYY'), 1);
INSERT INTO PEDIDO (NR_PEDIDO, DT_PEDIDO, FK_ID_CLIENTE) VALUES (2, TO_DATE('03.12.2005','DD.MM.YYYY'), 1);
INSERT INTO PEDIDO (NR_PEDIDO, DT_PEDIDO, FK_ID_CLIENTE) VALUES (3, TO_DATE('03.12.2010','DD.MM.YYYY'), 2);
INSERT INTO PEDIDO (NR_PEDIDO, DT_PEDIDO, FK_ID_CLIENTE) VALUES (4, TO_DATE('03.12.2011','DD.MM.YYYY'), 2);
COMMIT;
*/


CREATE OR REPLACE FUNCTION SF_RETORNA_QTD_PEDIDO(P_ID_CLIENTE NUMBER) RETURN VARCHAR2 IS
    V_ID_CLIENTE NUMBER(10):= &DIGITE_O_ID_CLIENTE;

    CURSOR C_PEDIDOS IS 
        SELECT C.NM_CLIENTE AS NOME, COUNT(P.NR_PEDIDO) QTD_PEDIDO
        FROM CLIENTE C INNER JOIN PEDIDO P 
        ON C.ID_CLIENTE = P.FK_ID_CLIENTE
        WHERE C.ID_CLIENTE = V_ID_CLIENTE
        GROUP BY C.NM_CLIENTE;

BEGIN
    FOR REG IN C_PEDIDOS LOOP
        DBMS_OUTPUT.PUT_LINE('NOME: ' || REG.NOME || 'QTD PEDIDOS: ' || REG.QTD_PEDIDO);
        DBMS_OUTPUT.PUT_LINE('');
        RETURN REG.QTD_PEDIDO;
    END LOOP;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Erro: ' || SQLCODE);
        DBMS_OUTPUT.PUT_LINE('Mensagem - ' || SQLERRM);

end;
